import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";
const origin="http://127.0.0.1:3100";
for (const width of [1200,390]) test(`learning: author, validate, publish and practice at ${width}px`,async({page,browser})=>{
  test.setTimeout(90000);await page.setViewportSize({width,height:900});
  const email=`e2e-${process.env.CHESS_E2E_RUN_ID}-${randomUUID()}@example.test`;
  expect((await page.request.post("/api/auth/sign-up/email",{headers:{origin},data:{name:"Learning tester",email,password:"learning browser passphrase"}})).status()).toBe(200);
  await page.goto("/learning");await page.getByRole("button",{name:"Add Mate in One sample"}).click();
  await expect(page.getByRole("heading",{name:"1001 chess exercises for beginners"})).toBeVisible();
  await page.getByRole("link",{name:"Mate in One",exact:true}).click();
  await expect(page.getByText("0 / 1 current exercises completed")).toBeVisible();
  await page.getByRole("link",{name:"1. The pin is mightier than the sword",exact:true}).click();
  await expect(page).toHaveURL(/\/learning\/exercises\/[^/?]+\?revision=[^/]+$/);
  await expect(page.getByRole("group",{name:/Puzzle position/})).toBeVisible();
  await page.screenshot({path:`test-results/learning-${width}.png`,fullPage:true});
  const id=new URL(page.url()).pathname.split("/").at(-1)!;
  const initial=(await (await page.request.get(`/api/learning/exercises/${id}`)).json()).puzzle;
  expect(initial.learning.publishedSolution).toBeNull();expect(initial.learning.explanation).toBeNull();expect(initial.solutionLine).toBeNull();
  await page.getByLabel("Move coordinates").fill("a1a4");await page.getByRole("button",{name:"Check move"}).click();
  await expect(page.getByRole("status",{name:"Puzzle feedback"})).toContainText("legal, but it is not a solution");
  const board=page.getByRole("group",{name:/Puzzle position/});await board.locator('[data-square="a1"]').click();await board.locator('[data-square="a6"]').click();
  await expect(page.getByText("First completion saved · Unassisted")).toBeVisible();
  await expect(page.getByText("Book solution: Rxa6#")).toBeVisible();await page.reload();await expect(page.getByText("First completion saved · Unassisted")).toBeVisible();
  await page.getByRole("link",{name:"Return to chapter"}).click();await expect(page.getByText("1 / 1 current exercises completed")).toBeVisible();
  await page.getByRole("link",{name:"Add exercise",exact:true}).click();
  await page.getByLabel("Exercise number",{exact:true}).fill("2");await page.getByLabel("Title",{exact:true}).fill("Another pin exercise");
  await page.getByRole("textbox",{name:"Full FEN",exact:true}).fill("kr6/1p6/p7/4b3/8/8/1P4BP/R6K w - - 0 1");
  await page.getByLabel("Published solution (SAN, one branch per line)",{exact:true}).fill("Rxa6#");
  await page.getByRole("button",{name:"Save draft",exact:true}).click();await expect(page.getByRole("status",{name:"Exercise authoring status"})).toContainText("Draft saved");
  await expect(page).toHaveURL(/\/learning\/exercises\/[^/]+\/edit$/);
  await expect(page.getByRole("heading",{name:"Edit exercise"})).toBeVisible();
  await page.getByRole("button",{name:"Preview first solution"}).click();await page.getByRole("button",{name:"Next move",exact:true}).click();await expect(page.getByRole("paragraph").filter({hasText:/^Rxa6#$/})).toBeVisible();
  await page.getByRole("button",{name:"Return to editing"}).click();
  await page.getByRole("button",{name:"Validate",exact:true}).click();await expect(page.getByRole("status",{name:"Exercise authoring status"})).toContainText("Validated");
  await page.getByRole("button",{name:"Publish",exact:true}).click();await expect(page.getByRole("status",{name:"Exercise authoring status"})).toContainText("Published");
  await expect(page).toHaveURL(/\/learning\/exercises\/[^/]+\/edit$/);
  const second=page.url().split("/").at(-2)!;
  await page.getByRole("link",{name:"Mate in One",exact:true}).click();await expect(page.getByText("1 / 2 current exercises completed")).toBeVisible();
  await page.getByRole("link",{name:"Resume chapter",exact:true}).click();await expect(page).toHaveURL(new RegExp(`/learning/exercises/${second}\\?revision=`));
  await page.getByRole("button",{name:"Reveal solution"}).click();await expect(page.getByText("Book solution: Rxa6#")).toBeVisible();await expect(page.getByText(/First completion saved/)).toHaveCount(0);
  await page.reload();await page.getByRole("button",{name:"Retry puzzle"}).click();await expect(page.getByRole("status",{name:"Puzzle feedback"})).toContainText("Starting position restored");
  await page.getByLabel("Move coordinates").fill("a1a6");await page.getByRole("button",{name:"Check move"}).click();await expect(page.getByText("First completion saved · Assisted")).toBeVisible();
  await page.getByRole("link",{name:"Return to chapter"}).click();await expect(page.getByText("2 / 2 current exercises completed")).toBeVisible();
  const other=await browser.newContext({baseURL:origin});
  try {
    expect((await other.request.get(`/api/learning/exercises/${id}`)).status()).toBe(401);
    expect((await other.request.post("/api/auth/sign-up/email",{headers:{origin},data:{name:"Other learner",email:`e2e-${process.env.CHESS_E2E_RUN_ID}-${randomUUID()}@example.test`,password:"other learning passphrase"}})).status()).toBe(200);
    expect((await other.request.get(`/api/learning/exercises/${id}`)).status()).toBe(404);
    expect((await other.request.post(`/api/learning/exercises/${id}?revision=${initial.learning.revisionId}`,{headers:{origin},data:{action:"REVEAL",expectedRevision:0,requestId:randomUUID()}})).status()).toBe(404);
    expect((await other.request.post("/api/learning",{headers:{origin},data:{kind:"validate",id,expectedRevision:0}})).status()).toBe(404);
  } finally {await other.close();}
  await page.goto("/learning/history");await expect(page.getByRole("heading",{name:"Exercise history"})).toBeVisible();await expect(page.getByText(/Revision 1 · Completed/)).toHaveCount(2);
});
