import { randomUUID } from "node:crypto";
import { test, expect } from "@playwright/test";
const origin = "http://127.0.0.1:3100";
for (const width of [1200, 390]) test(`missing piece: publish, place, reveal and resume at ${width}px`, async ({ page }) => {
  await page.setViewportSize({ width, height: 900 });
  const signup = await page.request.post("/api/auth/sign-up/email", { headers: { origin }, data: { name: "Placement tester", email: `e2e-${process.env.CHESS_E2E_RUN_ID}-${randomUUID()}@example.test`, password: "placement browser passphrase" } });
  expect(signup.status()).toBe(200);
  const create = async (data: object) => {
    const response = await page.request.post("/api/learning", { headers: { origin }, data });
    expect(response.status()).toBe(200); return response.json();
  };
  const material = await create({ kind: "material", title: "Missing piece browser test" });
  const chapter = await create({ kind: "chapter", materialId: material.id, title: "The missing piece", order: 0 });
  const exercise = await create({ kind: "exercise", chapterId: chapter.id, number: "187", title: "Add a knight and it’s mate", order: 0, content: { type: "MISSING_PIECE", placementPiece: "n", fen: "6rk/6pp/8/1p1b4/p7/3P4/PPP5/1K5R w - - 0 1", prompt: "Place a white knight to checkmate Black.", solutionText: "Ng6#" } });
  await page.goto(`/learning/exercises/${exercise.id}/edit`);
  await page.getByRole("button", { name: "Preview first solution" }).click();
  await page.getByRole("button", { name: "Next move", exact: true }).click();
  await expect(page.getByText("Placed on g6", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Return to editing" }).click();
  await page.getByRole("button", { name: "Validate", exact: true }).click();
  await expect(page.getByRole("status", { name: "Exercise authoring status" })).toContainText("Validated");
  await page.getByRole("button", { name: "Publish", exact: true }).click();
  await expect(page.getByRole("status", { name: "Exercise authoring status" })).toContainText("Published");
  await page.goto(`/learning/exercises/${exercise.id}`);
  const board = page.locator('[aria-label="Puzzle position, White at the bottom"]');
  await expect(board).toBeVisible();
  await expect(board.locator('[data-square="h1"] img')).toHaveAttribute("src", "/images/wr.png");
  await expect(page.getByText("Ng6#", { exact: true })).toHaveCount(0);
  await board.locator('[data-square="h8"]').click();
  await expect(page.getByRole("status", { name: "Puzzle feedback" })).toContainText("leaves your king safe");
  await page.getByText("Place by square", { exact: true }).click();
  await page.getByLabel("Placement square").fill("e4");
  await page.getByRole("button", { name: "Check placement" }).click();
  await expect(page.getByRole("status", { name: "Puzzle feedback" })).toContainText("does not give checkmate");
  await page.getByRole("button", { name: "Show hint" }).click();
  await expect(page.getByText(/Hint: place the missing piece on/)).toContainText("g6");
  await page.getByRole("button", { name: "Reveal solution" }).click();
  await expect(board.locator('[data-square="g6"] img')).toHaveAttribute("src", "/images/wn.png");
  await expect(page.getByText(/First completion saved/)).toHaveCount(0);
  await page.reload();
  await page.getByRole("button", { name: "Retry puzzle" }).click();
  await expect(board.locator('[data-square="g6"] img')).toHaveCount(0);
  await board.locator('[data-square="g6"]').click();
  await expect(page.getByText("First completion saved · Assisted")).toBeVisible();
  await page.reload();
  await expect(page.getByText("First completion saved · Assisted")).toBeVisible();
  await page.screenshot({ path: `test-results/learning-placement-${width}.png`, fullPage: true });
  await page.getByRole("link", { name: "Return to chapter" }).click();
  await expect(page.getByText("1 / 1 current exercises completed")).toBeVisible();
});
