"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { AccountMenu } from "@/components/auth/account-menu";
import { Icon, type IconName } from "./icon";
import styles from "./app-shell.module.css";
const groups: { label: string; items: { href: string; label: string; icon: IconName }[] }[] = [
  { label: "Play", items: [{ href: "/", label: "Dashboard", icon: "home" }, { href: "/games", label: "My games", icon: "games" }, { href: "/games/new", label: "Import game", icon: "import" }, { href: "/play", label: "Play an engine", icon: "games" }, { href: "/puzzles", label: "Puzzles", icon: "puzzles" }] },
  { label: "Study", items: [{ href: "/analysis", label: "Analysis", icon: "games" }, { href: "/openings", label: "Openings", icon: "games" }, { href: "/endgames", label: "Endgames", icon: "learning" }, { href: "/learning", label: "Learning", icon: "books" }, { href: "/learning/materials", label: "Study materials", icon: "learning" }, { href: "/learning/plan", label: "Weekly plan", icon: "plan" }] },
  { label: "Account", items: [{ href: "/profile", label: "Profile", icon: "profile" }, { href: "/settings", label: "Settings", icon: "settings" }] },
];
function Brand() { return <Link href="/" className={styles.brand}><span className={styles.mark} aria-hidden="true"><svg width="16" height="16" viewBox="0 0 18 18" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round"><path d="M9 3v3M7.5 4.5h3M5 14h8l1 2H4l1-2zM5 14c0-4.5 1-6.5 4-8 3 1.5 4 3.5 4 8"/></svg></span><span>Chess <span className={styles.light}>Coach</span></span></Link>; }
export function AppShell({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const booksPage = pathname === "/learning";
  const publicPage = ["/sign-in", "/register", "/account-recovery"].includes(pathname);
  const active = (href: string) => href === "/" ? pathname === "/" : href === "/puzzles" ? pathname.startsWith("/puzzles") || pathname.startsWith("/replay") : href === "/games" ? pathname.startsWith("/games") && pathname !== "/games/new" : href === "/learning/materials" ? pathname.startsWith("/learning/") && !["/learning/plan", "/learning/profile"].includes(pathname) : href === "/learning" ? pathname === "/learning" : pathname === href || pathname.startsWith(`${href}/`);
  if (publicPage) return <>{children}</>;
  return <><aside className={`${styles.sidebar} ${booksPage ? styles.booksSidebar : ""}`}><Brand /><nav className={styles.navigation} aria-label="App navigation">{groups.map(group => <div key={group.label}><p className={styles.sectionLabel}>{group.label}</p>{group.items.map(item => <Link key={item.href} href={item.href} aria-label={item.label} aria-current={active(item.href) ? "page" : undefined} className={`${styles.navItem} ${active(item.href) ? styles.active : ""}`}><Icon name={item.icon} size={16}/><span>{item.label}</span></Link>)}</div>)}</nav><div className={styles.footer}><AccountMenu showIdentity /></div></aside><header className={styles.mobileHeader}><Brand /><details className={styles.mobileAccount}><summary aria-label="Account menu"><Icon name="profile"/></summary><div><Link href="/play">Play an engine</Link><Link href="/analysis">Analysis</Link><Link href="/openings">Openings</Link><Link href="/endgames">Endgames</Link><Link href="/learning/materials">Study materials</Link><Link href="/learning/plan">Weekly plan</Link><Link href="/settings">Settings</Link><AccountMenu /></div></details></header><div className={`${styles.content} ${booksPage ? styles.booksContent : ""}`}>{children}</div><nav className={styles.mobileNav} aria-label="Mobile navigation">{[{ href: "/", label: "Home", icon: "home" }, { href: "/games", label: "Games", icon: "games" }, { href: "/puzzles", label: "Puzzles", icon: "puzzles" }, { href: "/learning", label: "Learn", icon: "learning" }, { href: "/profile", label: "Account", icon: "profile" }].map(item => <Link key={item.href} href={item.href} aria-label={item.label} aria-current={active(item.href) ? "page" : undefined} className={active(item.href) ? styles.active : ""}><Icon name={item.icon as IconName} size={22}/><span>{item.label}</span></Link>)}</nav></>;
}
